export type Restaurant = {
  name: string;
  address: string;
  cityArea: string;
  cuisine: string;
  veganOptions: string;
  jRating: number;
  notes: string;
};

export const veganRestaurants: Restaurant[] = [
  {
    name: "Doh",
    address: "115 King St, Glasgow G1 5RB",
    cityArea: "Centre",
    cuisine: "Bakery",
    veganOptions: "good options",
    jRating: 10,
    notes: "best vegan doughnuts I've had",
  },
  {
    name: "The Dorky French",
    address: "39 Parnie St, Glasgow G1 5RJ",
    cityArea: "Centre",
    cuisine: "Bakery",
    veganOptions: "vegan",
    jRating: 10,
    notes: "best vegan pastries I've had in Scotland",
  },
  {
    name: "C'mon Inn Hot Pot & Korean BBQ Glasgow",
    address: "65 Cambridge St, Glasgow G3 6QX",
    cityArea: "Centre",
    cuisine: "Chinese",
    veganOptions: "options",
    jRating: 10,
    notes:
      "best hot pot I've had outside china; need a chinese speaker to explain the staff what I can eat",
  },
  {
    name: "Absent Ear",
    address: "Brunswick St, Glasgow G1 1TF",
    cityArea: "Centre",
    cuisine: "Drinks",
    veganOptions: "N/A",
    jRating: 10,
    notes: "love everything about it",
  },
  {
    name: "House of God",
    address: "65 Glassford St, Glasgow G1 1UP",
    cityArea: "Centre",
    cuisine: "Drinks",
    veganOptions: "N/A",
    jRating: 10,
    notes: "love for drinks and vibes; not had food",
  },
  {
    name: "Malo",
    address: "12 Bothwell St, Glasgow G2 6LU",
    cityArea: "Centre",
    cuisine: "Drinks",
    veganOptions: "options",
    jRating: 10,
    notes: "amazing drinks and service; great snacks",
  },
  {
    name: "The Alchemist",
    address: "Unit 2, George House, George Square, Glasgow G2 1EH",
    cityArea: "Centre",
    cuisine: "Drinks",
    veganOptions: "options",
    jRating: 10,
    notes: "love all the cocktails",
  },
  {
    name: "Dakhin",
    address: "89 Candleriggs, Merchant City, 91 Candleriggs, Glasgow G1 1NP",
    cityArea: "Centre",
    cuisine: "Indian",
    veganOptions: "good options",
    jRating: 10,
    notes: "best Indian I've had",
  },
  {
    name: "Paesano",
    address: "94 Miller St, Glasgow G1 1DT",
    cityArea: "Centre",
    cuisine: "Italian",
    veganOptions: "options",
    jRating: 10,
    notes: "as good as italian pizza",
  },
  {
    name: "Katsu",
    address: "53 W Nile St, Glasgow G1 2QB",
    cityArea: "Centre",
    cuisine: "Japanese",
    veganOptions: "good options",
    jRating: 10,
    notes: "love the decor; iconic spot; so many options",
  },
  {
    name: "Wagamama",
    address: "97 W George St, Glasgow G2 1PB",
    cityArea: "Centre",
    cuisine: "Japanese",
    veganOptions: "good options",
    jRating: 10,
    notes: "iconic japanese fats food; amazing vegan menu",
  },
  {
    name: "Chaophraya",
    address: "The Townhouse, Nelson Mandela Pl, Glasgow G1 2LL",
    cityArea: "Centre",
    cuisine: "Thai",
    veganOptions: "options",
    jRating: 10,
    notes: "such a nice place; food is superb",
  },
  {
    name: "Ocho",
    address: "8 Speirs Wharf, Glasgow G4 9TB",
    cityArea: "Northside",
    cuisine: "Brunch",
    veganOptions: "options",
    jRating: 10,
    notes: "super good brunch; actually interesting vegan options",
  },
  {
    name: "Suissi",
    address: "494 Dumbarton Rd, Glasgow G11 6SL",
    cityArea: "West End",
    cuisine: "Asian",
    veganOptions: "vegan",
    jRating: 10,
    notes: "SO GOOD",
  },
  {
    name: "Ottoman Coffeehouse",
    address: "73 Berkeley St., Glasgow G3 7DX",
    cityArea: "West End",
    cuisine: "Café",
    veganOptions: "options",
    jRating: 10,
    notes: "absolutely iconic pastry; great vibes",
  },
  {
    name: "Ox & Finch",
    address: "920 Sauchiehall St, Finnieston, Glasgow G3 7TF",
    cityArea: "West End",
    cuisine: "Contemporary",
    veganOptions: "good options",
    jRating: 10,
    notes: "love love love",
  },
  {
    name: "Rascal",
    address: "Upstairs, 1 Lynedoch St, Kelvingrove, Glasgow G3 6EF",
    cityArea: "West End",
    cuisine: "Drinks",
    veganOptions: "N/A",
    jRating: 10,
    notes: "cool place; really good cocktails",
  },
  {
    name: "Tabac",
    address: "10 Mitchell Ln, Glasgow G1 3NU",
    cityArea: "Centre",
    cuisine: "Bar",
    veganOptions: "N/A",
    jRating: 7,
    notes: "great cocktails; always busy",
  },
  {
    name: "Bread Meats Bread",
    address: "65 St Vincent St, Glasgow G2 5TF",
    cityArea: "Centre",
    cuisine: "Burgers",
    veganOptions: "options",
    jRating: 7,
    notes: "great burgers",
  },
  {
    name: "Rose & Grants",
    address: "27 Trongate, Glasgow G1 5EZ",
    cityArea: "Centre",
    cuisine: "Café",
    veganOptions: "good options",
    jRating: 7,
    notes: "nice brekkie; elite vegan scramble; drinks meh",
  },
  {
    name: "Absolute Roasters",
    address: "10 Waterloo St, Glasgow G2 6DA",
    cityArea: "Centre",
    cuisine: "Café",
    veganOptions: "options",
    jRating: 7,
    notes: "nice pastries, sells out fast",
  },
  {
    name: "Hide & Seek",
    address: "84 Buchanan St, Glasgow G1 3HA",
    cityArea: "Centre",
    cuisine: "Drinks",
    veganOptions: "N/A",
    jRating: 7,
    notes:
      "not 100% if this is the place I think it is - reinvestigation needed",
  },
  {
    name: "Kong",
    address: "23 Royal Exchange Square, Glasgow G1 3AJ",
    cityArea: "Centre",
    cuisine: "Drinks / Mix",
    veganOptions: "options",
    jRating: 7,
    notes: "really good vibes; roof terrace; good burgers + cocktails",
  },
  {
    name: "Amarone",
    address: "2 Nelson Mandela Pl, Glasgow G2 1BT",
    cityArea: "Centre",
    cuisine: "Italian",
    veganOptions: "options",
    jRating: 7,
    notes: "not italian italian; always had good food and service though",
  },
];
